---
kind: pipeline
name: default

steps:
  - name: gate-master
    image: bdebyl/alpine-git
    commands:
      - git fetch origin +refs/heads/master
      - git show-ref
      - git diff --name-only HEAD~1..HEAD | grep 'Dockerfile|src' || exit 78
    when:
      branch:
        - master

  - name: gate-pr
    image: bdebyl/alpine-git
    commands:
      - git fetch origin +refs/heads/master
      - git show-ref
      - git diff --name-only $(git merge-base refs/remotes/origin/master HEAD)..HEAD | grep 'Dockerfile|src' || exit 78
    when:
      branch:
        exclude:
          - master

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: bdebyl/awsddns
    when:
      branch:
        - master
---
kind: signature
hmac: c6f916c703c7add6514976544168f392fc592a1dc53cfd2ddfe3e8f23b216d39

...
