---
kind: pipeline
name: default

steps:
  - name: clone
    image: docker.io/bdebyl/alpine-git
    commands:
      - git clone https://github.com/bdebyl/docker-awsddns.git .
      - git checkout $DRONE_COMMIT
      - echo -n "1.0.$DRONE_BUILD_NUMBER" > .tags

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: bdebyl/awsddns
    when:
      branch:
        - master
---
kind: signature
hmac: fc33a4423c0c97e9b4b22791ae990b524897fc6b3cdbc9f9c2d62927d2ec3641

...
